# Generated by Django 5.1.7 on 2026-02-28 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('leader', models.CharField(blank=True, max_length=120)),
                ('members', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_national_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateField(default=django.utils.timezone.localdate)),
                ('image', models.FileField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='general', max_length=50)),
                ('message', models.TextField(max_length=1500)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_entity_accounts', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='ministry.entity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity__name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='ministry.entity')),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='posts/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=20)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ministry.post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT_1', 'Vice-president 1'), ('VICE_PRESIDENT_2', 'Vice-president 2'), ('TREASURER', 'Tresorier'), ('FINANCIAL_SECRETARY', 'Secretaire financier'), ('SECRETARY_GENERAL_1', 'Secretaire general 1'), ('SECRETARY_GENERAL_2', 'Secretaire general 2'), ('COUNSELOR_1', 'Conseiller 1'), ('COUNSELOR_2', 'Conseiller 2'), ('COUNSELOR_3', 'Conseiller 3'), ('COUNSELOR_4', 'Conseiller 4')], max_length=40)),
                ('member_name', models.CharField(max_length=120)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_members', to='ministry.entity')),
            ],
            options={
                'ordering': ['entity__name', 'role'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'role'), name='unique_role_per_entity')],
            },
        ),
    ]
