# Generated by Django 5.1.7 on 2026-02-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ISSUED', 'Émis'), ('SIGNED', 'Signé')], default='DRAFT', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('notes', models.TextField(blank=True)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='rentals.rental')),
            ],
        ),
    ]
